### ISSUE TITLE
Help with K1 mini

### ISSUE THREAD

**Issue by jeanniquini** [McMCCRU/minisatip-gx#2]
[root@gx6605s ~]# dmesg
5.040000] gxav_module_init: ok!
[    5.610000] DVB: registering new adapter (gxdvb)
[    5.610000] fe_profile.demod_type = 8
[    5.610000] fe_profile.demod_i2c_id = 0
[    5.620000] fe_profile.demod_chip_addr = 0xe4
[    5.620000] fe_profile.tuner_type = 55
[    5.630000] fe_profile.tuner_i2c_id = 0
[    5.630000] fe_profile.tuner_chip_addr = 0x18
[    5.630000]
[    5.630000] DEMOD, tuner register
[    5.650000] gx3211_init!!
[    5.650000]
[    5.650000] GX3211_GXDemod_Chanl_Rst
[    5.670000]
[    5.670000] DEMOD, GX3211_GXDemod_Init
[    5.670000] gx_i2c_open_dev(),find active i2c device,i2c_devid=0
[    5.830000] gx31x0_i2c_xfer() error : chipaddr: 0x0c, addr(one byte): 0x00, operatin: READ,
[    5.840000] RX: Error during I2C_RDWR ioctl with error code: -121
[    5.850000] RDA5815M I2C read error, ADDR: 24(0x18), REG:0(0x00), DATA: 0(0x00)
[    5.850000] read rda581x chip id err!
[    6.030000] gx31x0_i2c_xfer() error : chipaddr: 0x0c, addr(one byte): 0x01, operatin: READ,
[    6.040000] RX: Error during I2C_RDWR ioctl with error code: -121
[    6.050000] RDA5815M I2C read error, ADDR: 24(0x18), REG:1(0x01), DATA: 0(0x00)
[    6.060000] read rda581x chip id err!
[    6.060000] Read rda581x chip id 0x0 0x0
[    6.060000] DVB: registering frontend 0 (Nationalchip GX3211 DVB-C S2)...
[    6.150000] hello, GPIO!
[    6.260000] EHCI-NationalChip EHCI-NationalChip.0: EHCI-NationalChip
[    6.280000] EHCI-NationalChip EHCI-NationalChip.0: new USB bus registered, assigned bus number 1
[    6.310000] EHCI-NationalChip EHCI-NationalChip.0: irq 59, io mem 0x00900000
[    6.330000] EHCI-NationalChip EHCI-NationalChip.0: USB 0.0 started, EHCI 1.00, driver 10 Dec 2004
[    6.380000] usb usb1: configuration #1 chosen from 1 choice
[    6.400000] hub 1-0:1.0: USB hub found
[    6.400000] hub 1-0:1.0: 2 ports detected
[    6.820000] usb 1-2: new high speed USB device using EHCI-NationalChip and address 2
[    6.960000] ohci_hcd: 2006 August 04 USB 1.1 'Open' Host Controller (OHCI) Driver
[    7.060000] usb 1-2: configuration #2 chosen from 2 choices
[    7.070000] ohci_hcd_gx_drv_probe, a00000.
[    7.070000] OHCI-NationalChip OHCI-NationalChip.0: OHCI-NationalChip
[    7.120000] OHCI-NationalChip OHCI-NationalChip.0: new USB bus registered, assigned bus number 2
[    7.120000] OHCI-NationalChip OHCI-NationalChip.0: irq 58, io mem 0x00a00000
[    7.170000] eth0: register 'cdc_ether' at usb-EHCI-NationalChip-2, CDC Ethernet Device, 00:0e:09:86:8b:6f
[    7.270000] usb usb2: configuration #1 chosen from 1 choice
[    7.380000] hub 2-0:1.0: USB hub found
[    7.380000] hub 2-0:1.0: 1 port detected
[    7.750000] ohci_hcd_gx_drv_probe, b00000.
[    7.750000] OHCI-NationalChip OHCI-NationalChip.1: OHCI-NationalChip
[    7.810000] OHCI-NationalChip OHCI-NationalChip.1: new USB bus registered, assigned bus number 3
[    7.810000] OHCI-NationalChip OHCI-NationalChip.1: irq 57, io mem 0x00b00000
[    8.010000] usb usb3: configuration #1 chosen from 1 choice
[    8.100000] hub 3-0:1.0: USB hub found
[    8.100000] hub 3-0:1.0: 1 port detected
[    8.620000] Monitor Driver, (c) 2013 Technologies
[    8.880000] Init Internal TS interface for gx6605s.
[    8.880000] Use Internal TS interface in force parallel mode!!!!
[   14.890000] tune mode = 0
[   14.890000]
[   14.890000] GX3211_GXDemod_Chanl_Rst
[   14.910000]
[   14.910000] MODE SELECT---------------------
[   14.910000]
[   14.910000] GX3211_GX1132_Init_Chip
[   73.090000] Init Internal TS interface for gx6605s.
[   73.090000] Use Internal TS interface in force parallel mode!!!!
[   73.260000] gx31x0_i2c_xfer() error : chipaddr: 0x0c, addr(one byte): 0x04, operatin: WRITE,
[   73.260000] TX: Error during I2C_RDWR ioctl with error code: -121
[   73.270000] RDA5815M I2C write error, ADDR: 24(0x18), REG:4(0x04), DATA: 4(0x04)
[   73.300000] [rda581x_rda5817_init:245] tuner init fail!

**Comment by McMCCRU** [comment]
Hi!
What is your firmware version? It's Koqit K1 mini? Log from my working device...

```
[    5.050000] gxav_module_init: ok! 
[    5.620000] DVB: registering new adapter (gxdvb)
[    5.620000] fe_profile.demod_type = 8
[    5.620000] fe_profile.demod_i2c_id = 0
[    5.630000] fe_profile.demod_chip_addr = 0xe4
[    5.630000] fe_profile.tuner_type = 55
[    5.640000] fe_profile.tuner_i2c_id = 0
[    5.640000] fe_profile.tuner_chip_addr = 0x18
[    5.640000] 
[    5.640000] DEMOD, tuner register
[    5.660000] gx3211_init!!
[    5.660000] 
[    5.660000] GX3211_GXDemod_Chanl_Rst
[    5.680000] 
[    5.680000] DEMOD, GX3211_GXDemod_Init
[    5.680000] gx_i2c_open_dev(),find active i2c device,i2c_devid=0
[    5.690000] Read rda581x chip id 0x58 0xf8
[    5.690000] DVB: registering frontend 0 (Nationalchip GX3211 DVB-C S2)...
```

Either your set-top box is faulty, or it is a new revision with a different tuner chip. You will have to disassemble your set-top box and see name tuner chip, or save log when native firmware is running.

**Comment by jeanniquini** [comment]
Hi! Yes.
FW: GXSATIP-V.1.0.11_1_30082020181755
I changed the firmware before I knew it ... Removing the shield from the tuner can I identify the model?

![20201210_161835](https://user-images.githubusercontent.com/43561057/101820442-62006380-3b05-11eb-987c-003dc71a3434.jpg)

**Comment by jeanniquini** [comment]
Specs: 

![20201210_164242](https://user-images.githubusercontent.com/43561057/101821561-e2739400-3b06-11eb-8b8d-d0b52f0e05c9.jpg)

**Comment by McMCCRU** [comment]
You have a different board. The tuner chip you have is not RDA5815M, but AV2018, it is written right on the board - GX6605S-**AV2018**-MINI-5#-Ver.1.1. You need to specify a different frontend initialization in the settings - FE_PROFILE="|8:0:0xe4:41:0:0xc6:&1:1:2:0:0:1"

**Comment by McMCCRU** [comment]
![Screenshot_20201210_230815](https://user-images.githubusercontent.com/14278314/101824019-b2df7e80-3b3c-11eb-82cd-bfea9030dc70.png)

**Comment by jeanniquini** [comment]
Working. I'm already scanning the channels on tvheadend. Thank you so much.

**Comment by McMCCRU** [comment]
Excellent! Then I close this issue...

**Comment by zefie** [comment]
@jeanniquini were you able to get channel scanning to work, and if so, how? 

I have the same exact model board, using the FE_CONFIG string here does seem to help, but when I use any SAT IP Software (DVBViewer, ProgDVB, TVHeadEnd), and hit scan on the transponder, I can see in the debug log that minisatip is finding the PMT, and even sending it over UDP, but apparently against spec, or for some other reason is not being seen by the target software. 

I am able to stream a specific PID via Media Player Classic, but literally every other Sat>IP function does not work (no raw TS streams, no EPG, no transponder scanning, etc)

I assume there are some GX-specific flags I need to set but I cannot figure out the bit mask documentation.

**Comment by jeanniquini** [comment]
I can help you with tvheadend. Show me your satip settings in the 'DVB Inputs' tab.

**Comment by zefie** [comment]
Thanks for the reply. I am not really interested in TVHeadend itself, but tried it to see what was up. Optimally I would like a raw TS of the entire TP to be sent from the demod.

**Comment by McMCCRU** [comment]
Hi! This project was originally created to work with tvheadend and not tested with other programs...

**Comment by zefie** [comment]
@McMCCRU Thanks for the reply. You seem to know a fair bit about the GX6605 chip, is what I am trying to do even possible?

I been trying to run the demod in serial mode but regardless of the -A number I provide, it still says "init in force parallel". I am not even sure serial mode would accomplish my goal.

My goal is to get the demod to send the entire TP, not just PID slices, which would essentially turn these boxes into the RTL-SDR of sat analysis, removing, or at least reducing, the $250+ TBS card cost barrier for any decent satellite browsing and analyzing.

I did make a [scanning script for PID mode](https://gist.github.com/zefie/87fc4a3d469b38a7922aef93e1890edc) but it is a bit slow and tedious.

Thanks for your progress so far on this fork, and thanks for any insight you may or may not be able to offer.

**Comment by McMCCRU** [comment]
My attempts to get a stream of the entire multiplex were unsuccessful. This chip does not support this feature.

**Comment by zefie** [comment]
> My attempts to get a stream of the entire multiplex were unsuccessful. This chip does not support this feature.

That is a shame. Do we know it is outright unsupported, or is it possible something has yet to be discovered? Could it be a limitation of the fe kernel driver? Could there be some unknown i2c bits that enable it? Or a complete demod bypass to give us raw I/Q from the tuner. 

From what I understand we are working with a kernel from a binary firmware release, right? So perhaps the limitation is in their driver, since they only had to implement it to work with their firmware. Or one can hope.

I would like to experiment more but I am unsure how you got your uImage, as all of the binaries I have found have some eCos (encrypted?) kernel.

**Comment by McMCCRU** [comment]
This chip also has a limited pids list of 32. The demultiplexer is not controlled over i2c, everything happens in the driver through registers SoC, I have no such information.

**Comment by zefie** [comment]
Which clone manufacture did you get your uImage from? I'd like to try to bug them with GPL to get some code.

**Comment by McMCCRU** [comment]
There was a linux-based firmware from hellobox s2, but now they are using ecos.
