### ISSUE TITLE
Upstreaming your code

### ISSUE THREAD

**Issue by danielkucera** [McMCCRU/minisatip-gx#3]
Hi,

I've dared to create PR in the original https://github.com/catalinii/minisatip/pull/800
I hope you are okay with that.

**Comment by danielkucera** [comment]
And where can one get GXAPI header files? It might be problematic to having them included in minisatip so it would be better to get them separately from other source

**Comment by McMCCRU** [comment]
Hi! I don't think my minisatip version will work with other chips NationalChip... I do not know where to find other header files, everything that I managed to find is in the minisatip-gx.

**Comment by danielkucera** [comment]
Do you have full kernel sources?
```
[    0.000000] Linux version 2.6.27.55 (igor@igor-GL553VE) (gcc version 4.5.1 (C-SKY Tools V2.8.01-gx-sp9(UClibc), ABIV1, B20170724) ) #3 Sun May 24 19:40:53 MSK 2020
```
Can you share?

**Comment by McMCCRU** [comment]
No... I myself corrected it in the unpacked kernel in hex-editor and packed it back. :)

**Comment by danielkucera** [comment]
Are you serious? Can you please contact me on e-mail in my profile?

**Comment by McMCCRU** [comment]
Any difficulties with this? Here are original files that I corrected with hex-editor.
[old_orig_files.zip](https://github.com/McMCCRU/minisatip-gx/files/5896934/old_orig_files.zip)
