### ISSUE TITLE
Building fullflash

### ISSUE THREAD

**Issue by danielkucera** [McMCCRU/minisatip-gx#4]
How do you build fullflash image? build.sh builds only minisatip binary.

Thanks.

**Comment by McMCCRU** [comment]
Hi! 
I do not have the source code, to build the firmware I used the information that I could find on the Internet. I posted a firmware collector to which you can add something of your own ... 
https://github.com/McMCCRU/gx6605s_linux_fw_build
https://github.com/McMCCRU/gx66xx

**Comment by danielkucera** [comment]
thanks
