### ISSUE TITLE
How to enable the network?

### ISSUE THREAD

**Issue by lars18th** [McMCCRU/minisatip-gx#5]
Hi,

Please, can you share in the homepage or in the Wiki section how to add a network interface?

Thank you!

**Comment by McMCCRU** [comment]
Hi!
All discussions are available only on the Russian-language archive forum http://old-forum.alexelec.tv/viewtopic.php?f=22&t=5309 , use the translator. Continuation of this forum here - https://forum.alexelec.tv/index.php?topic=87.0
Almost any USB-Ethernet adapter or wifi adapters will do, the list of which is in the archives with firmware.
